# Generated by Django 2.2.3 on 2021-03-22 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0004_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=250)),
                ('precio', models.CharField(max_length=10)),
                ('fecha', models.CharField(default=datetime.date(2021, 3, 22), max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a.Usuario')),
            ],
        ),
    ]
