# Generated by Django 2.2.3 on 2021-03-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0005_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cantidad',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
