# Generated by Django 2.2.3 on 2021-03-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0006_factura_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='referencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refe', models.CharField(max_length=1000)),
            ],
        ),
    ]
