# Generated by Django 2.2.3 on 2021-03-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0007_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='formaPago',
            field=models.CharField(default='', max_length=50),
        ),
    ]
